### ISSUE TITLE
File types configuration support

### ISSUE THREAD

**Issue by kosz78** [oderwat/vscode-indent-rainbow#1]
It will be fine provide some configuration to include or exclude file types from indent coloring. for example to apply indent coloring only for nim, python file types

**Comment by oderwat** [comment]
Yes indeed! Thats on top of my todo list!

I was thinking about adding it in the first release but then I didn't saw a major problem with it being active everywhere for now.

**Comment by oderwat** [comment]
I added some configuration setting. I am not sure if the way I do it is the best one, at least it works and should perform well enough.
