### ISSUE TITLE
HSLA in default configuration.

### ISSUE THREAD

**Issue by josemadriz** [oderwat/vscode-indent-rainbow#10]
I'm using hsla for the colors.
you should use them in the defaults :)
`
	"indentRainbow.colors": [
		"hsla( 70, 100%, 50%, 0.35)",
		"hsla(130, 100%, 50%, 0.35)",
		"hsla(190, 100%, 50%, 0.35)",
		"hsla(250, 100%, 50%, 0.35)",
		"hsla(310, 100%, 50%, 0.35)",
		"hsla( 10, 100%, 50%, 0.35)"
	]
`

**Comment by oderwat** [comment]
No I like what I have. Thank you!
