### ISSUE TITLE
Doesn't seem to work anymore

### ISSUE THREAD

**Issue by QDelage** [oderwat/vscode-indent-rainbow#100]
I just updated my extension to version 7.5.0 (from 7.4.0) on VSCodium 1.52.1, on ArchLinux 64bits.
And it doesn't seem to work anymore. (It just doesn't color anything anymore)
I went back to the last version and it works perfect.

The open VSX registry doesn't seem to provide the changelog so I'm not sure what changes were made from the last version to this one.

**Comment by lolouk44** [comment]
probably related, just install vscode and tried to install the extension and it states `Unable to install extension 'oderwat.indent-rainbow' as it is not compatible with VS Code '1.51.1'.`

**Comment by oderwat** [comment]
I run it on 1.52.1, and the extension is compiled with a 1.52.0 target. So I guess it has to do with the version of VSCode. I had changed to a newer version of the skeleton, which may bring a problem. I would suggest using 7.4.0 until a solution is found.

**Comment by oderwat** [comment]
It would be interesting if it works with VSCode under Linux. I actually didn't know about VSCodium until today.

**Comment by kennykingdev** [comment]
I'm just trying this extension for the first time so I can't confirm it would have worked before v7.5.0, but it is not working in Code - OSS under Linux for me.

Version info from Code:
```
Version: 1.52.1
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-19T14:42:39.893Z
Electron: 9.4.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.10.3-arch1-1
```

**Comment by oderwat** [comment]
@kennykingdev So install/downgrade to 7.4.0. I don't know why it does not work with the Linux version of VSCode (or is it just not working with VSCodium?). It should be identical to the others. I tested Mac and Windows versions of the current VSCode, and it works as expected.

**Comment by lolouk44** [comment]
interesting thing for me, downloading and manually installing the extension on my container failed, but searching and installing via GUI worked...

**Comment by AnthonyLzq** [comment]
In my case, I also had to downgrade to the version [7.4.0](https://github.com/oderwat/vscode-indent-rainbow/blob/cdcede40f09201f9a63643a64039e4df155316de/indent-rainbow-7.4.0.vsix) (in this link you can download the .vsix file required for that). For those who doesn't kwon how to do that, you can run the following command on your terminal:

```
code --install-extension indent-rainbow-7.4.0.vsix --force
```

I hope it helps.

**Comment by oderwat** [comment]
Why so complicated?
![image](https://user-images.githubusercontent.com/719156/104209756-671d3f00-5432-11eb-8736-8a0183506fc7.png)

Why not select another version from the plugin's editor inside the editor?

**Comment by oderwat** [comment]
What version of VSCode are you using @AnthonyLzq ? Also VSCronium on Linux or something else?

**Comment by AnthonyLzq** [comment]
> Why so complicated?
> ![image](https://user-images.githubusercontent.com/719156/104209756-671d3f00-5432-11eb-8736-8a0183506fc7.png)
> 
> Why not select another version from the plugin's editor inside the editor?

Lol, my bad, I didn't know that was possible.

**Comment by AnthonyLzq** [comment]
> What version of VSCode are you using @AnthonyLzq ? Also VSCronium on Linux or something else?

I'm using [code](https://archlinux.org/packages/?name=code) for Arhclinux, here is the requested data:

```
Version: 1.52.1
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-19T14:42:39.893Z
Electron: 9.4.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.10.2-2-MANJARO
```

**Comment by oderwat** [comment]
@AnthonyLzq I wonder if it would work with https://aur.archlinux.org/packages/visual-studio-code-bin/

**Comment by Code47X** [comment]
Can confirm. The latest version was broken for me on both VScodium (the package linked above) as well as the Code - OSS from the official repositories. Archlinux.

Downgrading the version did fix it for me.

**Comment by oderwat** [comment]
Strange thing, as this is based on the official extension skeleton, you get with the current scaffolding tool. There are also no reports from other systems, and I tested it on Windows and OSX myself. May need to set up a local Archlinux for investigation.

**Comment by AnthonyLzq** [comment]
> @AnthonyLzq I wonder if it would work with https://aur.archlinux.org/packages/visual-studio-code-bin/

It worked. Thanks for the advice.

**Comment by jezekus** [comment]
Hello just to inform, I have been trying to solve same issue and came across this ticket.
Having same issue on Fedora 33 and VSCodium 1.52.1, installing older 7.4.0 version of add-on worked as workaround.

```
Version: 1.52.1
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-17T00:37:39.556Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.10.6-200.fc33.x86_64
```

**Comment by oderwat** [comment]
This seems to be a problem with VSCodium, and I don't want to analyze it because the update was also meant to be based on the new extension skeleton after the last version was compiled for version 0.51 of VSCode, years ago. If somebody invests the time to find out what actually happens, I may adjust it. But as for now, I am still with more than 1.5 million downloads and zero donations. There is always the older version. I also did not yet receive a complaint from users of the official VSCode release.

**Comment by snowman** [comment]
> In my case, I also had to downgrade to the version [7.4.0](https://github.com/oderwat/vscode-indent-rainbow/blob/cdcede40f09201f9a63643a64039e4df155316de/indent-rainbow-7.4.0.vsix) (in this link you can download the .vsix file required for that). For those who doesn't kwon how to do that, you can run the following command on your terminal:
> 
> 
> ```
> code --install-extension indent-rainbow-7.4.0.vsix --force
> ```
> 
> I hope it helps.

Thanks, it works by downgrade version from `7.5.0` to `7.4.0`!!

**Comment by jinnko** [comment]
Has the cause in VSCodium or Code OSS been identified for this?

I'm on ArchLinux with the latest Code OSS and downgrading to 7.4.0 got things working.

**Comment by oderwat** [comment]
No, and I don't care. The upgrade actually was for getting in line with the current extension skeleton. If that does not work with third-party implementations, I personally won't invest time to investigate this, especially with 1.6 million downloads and zero donations.

**Comment by QDelage** [comment]
Well, it seems to have solved itself with last VSCodium update, so I guess it was due to the version or something like that.
Anyway, thank you for your work on this extension!

**Comment by oderwat** [comment]
That is great to hear!

**Comment by scollovati** [comment]
> 
> 
> Well, it seems to have solved itself with last VSCodium update, so I guess it was due to the version or something like that.
> Anyway, thank you for your work on this extension!

I'm on version 1.54.3 on W10 and still experiencing the issue with version 7.5.0 of the extension. Downgrading works fine!

**Comment by QDelage** [comment]
> > Well, it seems to have solved itself with last VSCodium update, so I guess it was due to the version or something like that.
> > Anyway, thank you for your work on this extension!
> 
> I'm on version 1.54.3 on W10 and still experiencing the issue with version 7.5.0 of the extension. Downgrading works fine!

Same version of VScodium but on ArchLinux and with VSCode Marketplace. I can't help you on that sorry. But downgrade, or try solving the bug. I'm a beginner and I don't understand much of the code so I can't really help personnaly...
