### ISSUE TITLE
Undocumented Setting ```indentSetter```

### ISSUE THREAD

**Issue by dalgibbard** [oderwat/vscode-indent-rainbow#101]
Hey there, just looking into the settings for this plugin to see if I can configure 2-space indents for some things (Javascript/Terraform), whilst retaining 4-space indenting for others (Python), and came across the setting param: ```indentRainbow.indentSetter```.

The description for this in ```package.json``` says to check the README.md for more info, but it's not documented there.

Would you be able to explain this setting, and whether it would enable the behaviour mentioned above?

Thanks in advance!

**Comment by oderwat** [comment]
Those were experimental and had been deprecated as this functionality is out of the scope of this plugin.

**Comment by dalgibbard** [comment]
Dang, would have loved that tbh! Thanks for the quick reply though :)
