### ISSUE TITLE
Colored in 2 when the indent setting is 4

### ISSUE THREAD

**Issue by ahao430** [oderwat/vscode-indent-rainbow#103]
The project indent is 4 spaces in js, as the editorconfig and eslint config. But still colored every 2 spaces.

**Comment by oderwat** [comment]
It uses what VSCode reports. Which means that the problem must be somewhere else.

**Comment by ovspianist** [comment]
I have got the same issue, using prettier as formatter.

**Comment by Mirrors406** [comment]
I have the same problem, and I deal it by open VSCode Settings, find the option "Editor: Tab Size", and there are a link to "Editor: Detect Indentation" click and close it.

**Comment by Mirrors406** [comment]
> I have the same problem, and I deal it by open VSCode Settings, find the option "Editor: Tab Size", and there are a link to "Editor: Detect Indentation" click and close it.



> I have got the same issue, using prettier as formatter.

I have the same problem, and I deal it by open VSCode Settings, find the option "Editor: Tab Size", and there are a link to "Editor: Detect Indentation" click and close it.

**Comment by Mirrors406** [comment]
> I have got the same issue, using prettier as formatter.

I have the same problem, and I deal it by open VSCode Settings, find the option "Editor: Tab Size", and there are a link to "Editor: Detect Indentation" click and close it.
