### ISSUE TITLE
Not working for Scala

### ISSUE THREAD

**Issue by bbstilson** [oderwat/vscode-indent-rainbow#104]
After a fresh install of version 7.5.0, it does not appear to be working.

<img width="272" alt="image" src="https://user-images.githubusercontent.com/7949037/114290205-a7408d80-9a32-11eb-9d49-9f0a1259a4b4.png">

Happy to provide more details. Let me know what might help.

**Comment by oderwat** [comment]
Sorry, butt I don't care.

**Comment by nuukedo29** [comment]
Based holy fuck lmao

**Comment by oderwat** [comment]
> Based holy fuck lmao

When you write software that has 2.1 million installs and with one single person sending a donation, you may just not care about a problem when somebody is using your plugin in another than the original product (vscodium was the culprit affair).

**Comment by nuukedo29** [comment]
> 
> 
> > Based holy fuck lmao
> 
> When you write software that has 2.1 million installs and with one single person sending a donation, you may just not care about a problem when somebody is using your plugin in another than the original product (vscodium was the culprit affair).

i agree. 

is this only affecting scala or all vscodium? i've migrated recently to new laptop and indent rainbows got fucked.

If its vscodium i can throw you 100$ in BTC/ETH to fix it, im too busy working on a project where its miserable without this plugin

**Comment by oderwat** [comment]
As far as I remember the vscodium problem was fixed by one of their updates. The language itself should not matter at all, so it can't be a scale problem. I fear if there is still a problem with vscodium or the Eclipse editor which also can use their plugins I still don't care. Afaik you can also simply install the previous version of the plugin, which is pretty easy to do afaik.

**Comment by nuukedo29** [comment]
> 
> 
> As far as I remember the vscodium problem was fixed by one of their updates. The language itself should not matter at all, so it can't be a scala problem. I fear if there is still a problem with vscodium or the Eclipse editor which also can use their plugins I still don't care. Afaik you can also simply install the previous version of the plugin, which is pretty easy to do afaik.

i'll donate you regardless, just don't have any fiat money.

i could only find credit card donation button, if you send your ETH or BTC address i could donate some of it.

**Comment by oderwat** [comment]
Well, thanks but I pass. I actually prefer monopoly money xD.

**Comment by nuukedo29** [comment]
![image](https://user-images.githubusercontent.com/55753080/125371351-1b5f3a00-e370-11eb-880a-2593fbbb1708.png)
