### ISSUE TITLE
suggestion: add an option to only care about tabs, ignore spaces

### ISSUE THREAD

**Issue by xaxazak** [oderwat/vscode-indent-rainbow#105]
Some of us use tabs for indent and spaces for alignment. Unfortunately, indent-rainbow colorizes alignment spaces as indents or errors.

I guess the easiest way to prevent this would be to add an option to treat spaces like other characters (eg letters). This would also help to identify when spaces are accidentally used as indents, because they won't get colorized).

**Comment by oderwat** [comment]
The only case I personaööy care about is covered by:

```
  // The indent color when there is a mix between spaces and tabs.
  // To be disabled this coloring set this to an empty string.
  "indentRainbow.tabmixColor": "rgba(128,32,96,0.6)"
```

I do not plan to invest any more time into a 1.9 million installations plugin with 0 (zero) donations.
