### ISSUE TITLE
Not seeing any colors at all after install

### ISSUE THREAD

**Issue by robbyki** [oderwat/vscode-indent-rainbow#113]
Not sure what setting I have that's clobbering the rainbow colors but after installation I don't see any indent rainbow in my scala file or any files for that matter.

**Comment by oderwat** [comment]
Strange. The default settings should show that anywhere. What Visual Studio Code version is being used?

**Comment by robbyki** [comment]
no difference with js. I'm on vscodium 1.59 and fedora 34.

**Comment by oderwat** [comment]
I don't want to support vscodium. This is a Visual Studio Code plugin. If they pretend to support this plugin, they should work on this. Not me.

**Comment by robbyki** [comment]
I understand. thanks for the help.
