### ISSUE TITLE
Extension contains entire VS Code Web within

### ISSUE THREAD

**Issue by joaomoreno** [oderwat/vscode-indent-rainbow#115]
Having manually downloaded the VSIX from https://marketplace.visualstudio.com/items?itemName=oderwat.indent-rainbow, I noticed there's a `.vscode-test-web` folder within, containing 50MB of data.

This folder should now [be ignored by default by vsce](https://github.com/microsoft/vscode-vsce/commit/c4acee2cd6fe59a2f48ac73456c3143fb561b747), starting from v1.100.0. Can you please republish your extension using this vsce version, such that that folder doesn't get included? Thanks!

**Comment by oderwat** [comment]
Actually I just did it quickly. Should update soon. Can you check if it worked (in 8.1.0 it should be gone now).

**Comment by joaomoreno** [comment]
Thanks @oderwat! Tell me about it, having pretty busy days over here as well...
