### ISSUE TITLE
match colors to the colors of the brackets

### ISSUE THREAD

**Issue by capaj** [oderwat/vscode-indent-rainbow#116]
since vscode now has colorisation of brackets: https://code.visualstudio.com/blogs/2021/09/29/bracket-pair-colorization

it would be very nice if the colors could match the brackets default set

**Comment by oderwat** [comment]
Interesting, but I actually would not change to those colors "by default". There are more than two million installs. Most of them are working with the current default values. Changing them may end up in a UX disaster.

But we could add a set of different colors to copy & paste into the documentation, so people can pick that easily if they want that schema.

**Comment by kconedera** [comment]
I decided to set up my colors to match my theme's bracket colors (I use Dracula).

It took a bit of extra work, but I basically went into the .yml source code of my theme and found the "editorBracketHighlight.foreground[1-6]" key/value pairs, e.g.:


    editorBracketHighlight.foreground1: *FG
    editorBracketHighlight.foreground2: *PINK
    editorBracketHighlight.foreground3: *CYAN


in which the *[COLOR] values are defined in an earlier code chunk, e.g.:


    - &FG '#F8F8F2'
    - &PINK '#FF79C6'
    - &CYAN '#8BE9FD'


Then I just used a website to convert the color hex values to rbg values, added my preferred "a" value (i.e., opacity of the color), and added those values in the same order to my settings.json files using the "indentRainbow.colors" key. Here's a copy of my .json data setting my indent colors as lines following the same colors as the Dracula theme, also making them brighter/more visible than the default (the "0.7" value in the rgba):


    "indentRainbow.indicatorStyle": "light",
    "indentRainbow.colors": [
      "rgba(248,248,242,0.7)",
      "rgba(255,121,198,0.7)",
      "rgba(139,233,253,0.7)",
      "rgba(80,250,123,0.7)",
      "rgba(189,147,249,0.7)",
      "rgba(255,184,108,0.7)"
    ],


The final product:
![image](https://user-images.githubusercontent.com/86323538/162638238-927f8fe7-4c0f-4194-a3ca-9242e03d7c99.png)

It would probably be relatively easy to operationalize this, or at the very least generate some copy/paste .json code for the built-in themes. If I have time I'll check it out.

Hope this helps somebody out there :)

**Comment by oderwat** [comment]
Well, this plugin was mostly created with languages that **do not use** curly braces but indentation in mind. Such as Python, YAML, Nim, Haskell, Makefiles, Markdown, Elixir, and so on.

The colors are meant to visualize the indentation depth (they may even have a shade related to the depth).

When the colors match those of the brackets they are just "some other colors" that are fitting the scheme. That they look "like their corresponding brackets" is only a coincidence.

If one would actually match them (level-wise) it would hardly make any sense. If you see the example from the VSCode documentation you see that the indentation level would use the same color (blue) for the second and third level and there is "no color" for the fourth level at all. So it will match sometimes but will not make much sense at other times.

But of course, everybody can use whatever colors he wants to use :)
