### ISSUE TITLE
How can I remove this color when adding space.

### ISSUE THREAD

**Issue by ayushiamazing** [oderwat/vscode-indent-rainbow#120]
Whenever I add space to the starting line in vs code, a red color line traces it. How can I remove it?
![image](https://user-images.githubusercontent.com/90521537/157028651-ebb4c760-3c6f-47fc-8e3f-5747e1a5b57a.png)
Tell me ASAP.
Thanks,

**Comment by oderwat** [comment]
Depends on what you really want. There are multiple ways explained in the documentation. If you ask me: You get rid of it by deleting those spaces ;-)

**Comment by ayushiamazing** [comment]
I have so many of them(the red line) in my crowded code. I can't delete all of them one by one.😅
Can you just tell me how can I get rid of it? Please😁!!!

**Comment by oderwat** [comment]
Just read the documentation. I can't tell if you want to have "no" error color at all (disable it for all file types) or just not for "all whitespace in a line" (define a pattern to disable it).

**Comment by ayushiamazing** [comment]
Thanks, it was because of the error color, I just set the transparency to 0.0 and it worked.
