### ISSUE TITLE
[Feature Request] z-index setting

### ISSUE THREAD

**Issue by marblewraith** [oderwat/vscode-indent-rainbow#121]
Can we get a setting that tweaks how the indents are rendered? For example:

![08_03_2022-05_12AM-BrightMinty](https://user-images.githubusercontent.com/45786628/157093319-89b0f041-95ad-4844-b1cd-8718e5ab3d91.png)

It'd be nice if the cursor line background (on line 566) rendered *on top* of indent-rainbow (i.e. make indent-rainbow lower in the z-index stack) so the cursor line background becomes 1 contiguous line.

**Comment by oderwat** [comment]
I don't have control over how it renders it. I only set the background color for white space at the indentation level.
