### ISSUE TITLE
Where to edit config file

### ISSUE THREAD

**Issue by Schullebernd** [oderwat/vscode-indent-rainbow#127]
Sry, I'm really not firm with configuring the extensions in visual studio. But where can I edit the config file for rainbow-indent to activate the 'light mode' in VS2022. In the settings there is no option to do this...

Thanks in advance!!!

**Comment by oderwat** [comment]
There should be. Are you sure you updated to 8.3.1 and restarted the editor?

<img width="1033" alt="image" src="https://user-images.githubusercontent.com/719156/162618756-6a5b5598-fb3c-470b-b658-3b88f99e624c.png">

**Comment by Schullebernd** [comment]
Ahh sry man, just see it, I installed it on my Visual Studio but it's from another developer and yours is for vscode only.
