### ISSUE TITLE
How to achieve the effect of the left in the picture

### ISSUE THREAD

**Issue by brucmao** [oderwat/vscode-indent-rainbow#130]
There is any way remove rainbow color blocks?  just show rainbow vertical line
![image](https://user-images.githubusercontent.com/6119652/170667502-734374e6-dfdc-4dd3-9e73-f5b1316e6baf.png)

**Comment by oderwat** [comment]
https://github.com/oderwat/vscode-indent-rainbow#light-mode-new-since-v830
