### ISSUE TITLE
How can show only color lines not color bars?

### ISSUE THREAD

**Issue by rogelioprieto** [oderwat/vscode-indent-rainbow#139]
I prefer that this extension shows **lines** (no color bars) beside the indent sections (you can see this [image](https://raw.githubusercontent.com/oderwat/vscode-indent-rainbow/master/assets/example.png)) In this image I want to appears like left part  but it appears like right part!

How can setup this?

**Comment by CYuSir** [comment]
The same question。

**Comment by oderwat** [comment]
The same answer as in #134 and #130 ...
