### ISSUE TITLE
Don't color indents when making a brace aligned parameter list

### ISSUE THREAD

**Issue by JasonSettings** [oderwat/vscode-indent-rainbow#145]
Hello!
Is there any way to manuipulate the extension so it stops coloring indents when I align parameters on a left brace?
The perfect way for me is if it would color only the first indentation level.

Here is a pic of what I DO NOT want to happen.

![image](https://user-images.githubusercontent.com/107097079/210063255-077225d4-35ea-4a47-ad50-7841211ccc6e.png)

**Comment by oderwat** [comment]
No.
