### ISSUE TITLE
Language List

### ISSUE THREAD

**Issue by nazarkryp** [oderwat/vscode-indent-rainbow#147]
How to specify properly language in included/excluded languages?
e.g: c# how i should know what to specify: cs, csharp, c#, c sharp?

**Comment by oderwat** [comment]
Just use the name that VSCode uses itself. It shows the name in the bottom right of the editor window when you load a file.

![cbvb-340BC9E8-F5AC-49E2-883B-9E7061D5F2D8](https://user-images.githubusercontent.com/719156/217524440-e11eab02-0af6-452e-8823-9d92977c0ba4.jpg)
