### ISSUE TITLE
Not sure how to make indent into blocks to lines

### ISSUE THREAD

**Issue by Minus10Celcius** [oderwat/vscode-indent-rainbow#148]
I want to make the indent into lines to make it more cleaner but I don't know how

**Comment by oderwat** [comment]
I wonder if you read the documentation?

**Comment by Minus10Celcius** [comment]
> 

I didn't really understand it, may you help me?

**Comment by oderwat** [comment]
This plugin has over 4 million installations, and I actually wonder what's the problem? It is all written in the README.

Maybe just add: `"indentRainbow.ignoreErrorLanguages": ["*"]` to your config.

This is my current config:

```
"indentRainbow.ignoreErrorLanguages" : [
    "*"
  ],
  "indentRainbow.ignoreLinePatterns": [
    "/[ \t]* [*]/g",
    "/[ \t]+[/]{2}/g"
  ],
  "indentRainbow.lightIndicatorStyleLineWidth": 1,
  "indentRainbow.indicatorStyle": "light",
  "indentRainbow.colors": [
    "rgba(255,255,64,0.3)",
    "rgba(127,255,127,0.3)",
    "rgba(255,127,255,0.3)",
    "rgba(79,236,236,0.3)"
  ],
  "indentRainbow.excludedLanguages" : [
    "plaintext"
  ],
```

**Comment by Minus10Celcius** [comment]
> This plugin has over 4 million installations, and I actually wonder what's the problem? It is all written in the README.
> 
> Maybe just add: `"indentRainbow.ignoreErrorLanguages": ["*"]` to your config.
> 
> This is my current config:
> 
> ```
> "indentRainbow.ignoreErrorLanguages" : [
>     "*"
>   ],
>   "indentRainbow.ignoreLinePatterns": [
>     "/[ \t]* [*]/g",
>     "/[ \t]+[/]{2}/g"
>   ],
>   "indentRainbow.lightIndicatorStyleLineWidth": 1,
>   "indentRainbow.indicatorStyle": "light",
>   "indentRainbow.colors": 
>     "rgba(255,255,64,0.3)",
>     "rgba(127,255,127,0.3)",
>     "rgba(255,127,255,0.3)",
>     "rgba(79,236,236,0.3)"
>   ],
>   "indentRainbow.excludedLanguages" : [
>     "plaintext"
>   ],
> ```

Ohh, ok. Thanks!

**Comment by Minus10Celcius** [comment]
update: shit, i was blind @oderwat sorry for wasting your time
