### ISSUE TITLE
Highlighted space in vscode 

### ISSUE THREAD

**Issue by Jacques2101** [oderwat/vscode-indent-rainbow#149]
How to delete the brown highlighted colour inside vscode ? I suppose that it comes from Indent-rainbow extension (because when I deleted it, I do not have it anymore). 

<img width="713" alt="Capture d’écran 2023-02-25 à 12 42 49" src="https://user-images.githubusercontent.com/49912455/221361925-b43ec3db-db4e-414b-8461-eee61b2a949d.png">

**Comment by oderwat** [comment]
This is the error color. Read the documentation.

**Comment by Jacques2101** [comment]
where is the documentation ? I can't find it

**Comment by oderwat** [comment]
https://github.com/oderwat/vscode-indent-rainbow#hiding-error-highlighting
