### ISSUE TITLE
Output window is colourised

### ISSUE THREAD

**Issue by BillDenton** [oderwat/vscode-indent-rainbow#16]
The text output window is colourised (for example build output). This isn't much use. Could you disable it (possibly add a toggle for in case it desired).

**Comment by oderwat** [comment]
Not for me? Do you have a screenshot?

**Comment by BillDenton** [comment]
It doesn't seem to happen until you click into the output window. Once you do that this extension plus [Rainbow Brackets](https://marketplace.visualstudio.com/items?itemName=2gua.rainbow-brackets) get applied. I had a similar problem before with [Highlight Trailing White Spaces](https://marketplace.visualstudio.com/items?itemName=ybaumes.highlight-trailing-white-spaces), this [issue](https://github.com/yifu/highlight-trailing-whitespaces/issues/2). A possibly similar problem in [VS Code ClearCase](https://marketplace.visualstudio.com/items?itemName=OpenNingia.vscode-clearcase); see this [issue](https://github.com/OpenNingia/vscode-clearcase/issues/15) which was fixed.

**Comment by oderwat** [comment]
OK. I try to reproduce and fix it asap.

**Comment by oderwat** [comment]
Can't reproduce and actually seems unrelated to this plugin.

**Comment by aaronliu0130** [comment]
So which plugin is it? I don't have any other plugins specified in BillDenton's comment

**Comment by tandr-ssn** [comment]
![Screenshot 2024-07-09 155645](https://github.com/oderwat/vscode-indent-rainbow/assets/120140905/28e17259-2f5a-4814-8d7d-36f91d0d64a4)

Golang testing output window
