### ISSUE TITLE
Lists with wrapped text in Markdown have incorrect tab highlighting

### ISSUE THREAD

**Issue by AaronAllBright** [oderwat/vscode-indent-rainbow#160]
When editing a Markdown document, indent errors aren't shown by default, but lines with less than one whole indent count still show an indent background. For example, a bulleted list with a wrapped line will cause this error:

![image](https://github.com/oderwat/vscode-indent-rainbow/assets/47489965/e7f3e846-6b1d-4976-b3ae-5f36ff1b2e9e)

**Comment by oderwat** [comment]
Right, it is not an error, but it is not the correct indentation given the current indentation settings, which seems to be 4 in your case. Either change it to the actual 2 you are using or switch the plugin off. I will not change anything about that.

**Comment by AaronAllBright** [comment]
No, it's not an incorrect indentation. It is common to indent wrapped lines in a bulleted list to begin under the text, not the  bullet for readability.

![image](https://github.com/oderwat/vscode-indent-rainbow/assets/47489965/a3639483-d78b-4187-ae60-e5929bb4a619)

**Comment by AaronAllBright** [comment]
It should be noted that the "rewrap" extension, vscode, and a markdown linter (markdownlint) all recognize the above markdown as correctly formatted.

**Comment by oderwat** [comment]
> Right, it is not an error, but it is not the correct indentation given the current indentation settings

Set your editor to use 2 spaces and everything will be fine.

**Comment by AaronAllBright** [comment]
No thank you. My tab size is prescribed by project settings and linter requirements of my org. So I'll have to disable your plugin. Thanks for responding.
