### ISSUE TITLE
indentSetter is not described and does not work

### ISSUE THREAD

**Issue by Ranamzes** [oderwat/vscode-indent-rainbow#162]
indentRainbow.indentSetter | Automatically change indent settings for languages (see README.md for details).
I didn't find a description in the readme

![code](https://github.com/oderwat/vscode-indent-rainbow/assets/88456236/7baab9ad-541e-403f-8c01-e392c97fcd82)

"python": { doesn't work either

**Comment by lolitsozzie** [comment]
Thanks for posting this @Ranamzes

**Comment by oderwat** [comment]
#101
