### ISSUE TITLE
Disable Redundant Indentations 

### ISSUE THREAD

**Issue by yoshim3to** [oderwat/vscode-indent-rainbow#163]
Hi there, I was wondering if there was a method for cleaning up redundant indentations, such as several tabs before a comment (or just comments in general)?

I've been messing around with the "Ignore Line Patterns" and "Color on White Space Only" settings to see if this was already implemented, but this seems to only create exceptions for error highlighting, so I was hoping for a similar feature to skip rendering indent colors when encountering certain RegEx patterns.

![image](https://github.com/oderwat/vscode-indent-rainbow/assets/52094752/530c0423-2912-4fcd-8bca-4bd98d22420e)

For example, I want the indentations in the red box to not be rendered because I don't really need to know which tab group my comments are in, and the code would look a lot cleaner without them (ideally it would just render the first orange indent).

Any help is appreciated, thanks for taking the time to read!

**Comment by oderwat** [comment]
Well, this plugin shows the indentations. It is not about "looking" a certain way.
