### ISSUE TITLE
Option to color entire line, not just whitespace

### ISSUE THREAD

**Issue by deefdragon** [oderwat/vscode-indent-rainbow#165]
My history of using this extension traces itself all the way back to the Java BlueJ editor, which has a similar concept as this extension, but with the difference of highlighting based mostly on scope.

Tho it would be the ideal, I'm guessing based on some of the other issues I read that it would be rather difficult to do syntax based highlighting from bracket to bracket/paren to paren.

Would it be technically possible to at least get an option to highlight the entire line that is at a given tab level however?

BlueJ's Highlighting
![maxresdefault-1718912094](https://github.com/oderwat/vscode-indent-rainbow/assets/3053654/19fb9736-feb3-4c8c-929c-9dee8a3af758)

**Comment by oderwat** [comment]
I do not really want to get into that. But can't you use https://marketplace.visualstudio.com/items?itemName=leodevbro.blockman ?

**Comment by deefdragon** [comment]
Didnt know an extension to do that existed now. TY. Closed.
