### ISSUE TITLE
empty lines not showing the colors

### ISSUE THREAD

**Issue by Aquarii** [oderwat/vscode-indent-rainbow#166]
the default lines are there but the colors aren't. (see the pic) any solution? 
![image](https://github.com/oderwat/vscode-indent-rainbow/assets/8092720/fc0ca38e-ef5c-4f39-90c9-11adc878088b)

**Comment by Aquarii** [comment]
it's because of "trim trailing whitespace" setting in vscode. but any way to fix it?

**Comment by oderwat** [comment]
No, and I don't want to have lines where no whitespace is in the file. It should reflect what is there. The "lines" mode also was not the original mode and if you use the plugin as originally designed you probably would not want to have "blocks of color" in those empty lines.

**Comment by Aquarii** [comment]
got it. though it'd be nice if there was an option for it.
