### ISSUE TITLE
Improve Clojure/ClojureScript support

### ISSUE THREAD

**Issue by InSuperposition** [oderwat/vscode-indent-rainbow#167]
Colors are off with Clojure/ClojureScript files:

<img width="847" alt="image" src="https://github.com/oderwat/vscode-indent-rainbow/assets/433871/be2b61d8-5d0f-4b82-b5c2-2d87473b5be8">

Clojure repo:
https://github.com/jacobobryant/eelchat

ClojureScript repo:
https://github.com/Respo/respo.cljs

**Comment by oderwat** [comment]
There is nothing "off". You have the error mode enabled and there are a lot of error ins the indentation. Read the documentation closely.
