### ISSUE TITLE
No documentation for indentRainbow.indentSetter

### ISSUE THREAD

**Issue by krnl0138** [oderwat/vscode-indent-rainbow#168]
In package.json default config it's said that configuration for `indentRainbow.indentSetter` can found in `README.md` file.
 Yet I wasn't be able to find any mention of it.
 I think, it would be helpful to add it
 
 "description": "Automatically change indent settings for languages (see README.md for details)."

**Comment by oderwat** [comment]
There is nothing like that. I removed if from the package.json. Thanks
