### ISSUE TITLE
Light mode doesn't work with Tabmix on Jupiter Notebook

### ISSUE THREAD

**Issue by dominhkhoi2002** [oderwat/vscode-indent-rainbow#170]
![1](https://github.com/oderwat/vscode-indent-rainbow/assets/96510139/0cd7c96f-1257-414f-acbb-a12f7585c24f)
![2](https://github.com/oderwat/vscode-indent-rainbow/assets/96510139/6296ab8e-8d76-4a32-bd73-e78caa72805c)

I tried to disable and enable tabmix but it still leave spaces on for loops. (1)
class and def indent still works fine (2)

**Comment by oderwat** [comment]
I don't understand what this is about. "tabmix" is for highlighting where at the beginning of a line are spaces + tabs used together, and I do not even know if the variant with the "lines" as colorization (which is not my original idea) has support for that.
