### ISSUE TITLE
Request: Option to use rainbow colors even when indentation doesn't match

### ISSUE THREAD

**Issue by Srekel** [oderwat/vscode-indent-rainbow#18]
I use clang-format and it doesn't always align things nicely to the 2 or 4 spaces, so there's a lot of red in my code.

I get why the error color is there, but for my use case it doesn't quite work. I can come up with three ways to configure the setting:

1) "color-full-error-line" (standard, what it ships with today)
2) "color-last-indent" (uses rainbow colors for all indent levels except for the very last, where the error is)
3) "color-error-disabled" (this is what I want, at least for a few projects)

(Feel free to come up with better names. :) And number 2 is very optional but I think it could be nice.)

**Comment by Srekel** [comment]
Just an image to show what it looks like. :)

![image](https://user-images.githubusercontent.com/1578924/28255967-b7c2e85e-6abd-11e7-8f8a-abfcb16b29b7.png)

**Comment by AndrewRayCode** [comment]
Yes. Plugin should snap color to nearest indent level, not do what it currently does.

**Comment by oderwat** [comment]
I disagree. The Plugin works as designed for what I need it. But a PR which allows multiple variants would probably be accepted.

**Comment by alexmironof** [comment]
Also same for `wrap-aligned` html attributes

**Comment by oderwat** [comment]
With 0.7.2. there is an option added to skip error highlighting for selected languages or all of them if you specify '*'.

**Comment by alexmironof** [comment]
@oderwat Nice thanks!
