### ISSUE TITLE
How to change style?

### ISSUE THREAD

**Issue by laserbeak** [oderwat/vscode-indent-rainbow#185]
Hello,
Probably a silly question, but I couldn't find/identify the answer reading the how-to on the extension page or going through the settings.
How do I make the indents look like the line-style on the left image on the extension's page and not the highlight on the right side?

![image](https://github.com/user-attachments/assets/525d5197-e8d2-424d-8593-d8a45b37b867)

**Comment by oderwat** [comment]
How about reading the documentation? https://github.com/oderwat/vscode-indent-rainbow?tab=readme-ov-file#light-mode-new-since-v830

**Comment by laserbeak** [comment]
Was just testing you. You've passed! Congratulations!!
