### ISSUE TITLE
[Suggestions] Light theme palette & Bracket color mode

### ISSUE THREAD

**Issue by Alyaqdhans** [oderwat/vscode-indent-rainbow#186]
I want to make the color sequence match the bracket colors, so.. in dark theme it works fine:
![image](https://github.com/user-attachments/assets/b41d93e3-f357-460f-aeb3-ecef4db17d2d)

But in light theme, the brackets are in different colors:
![image](https://github.com/user-attachments/assets/ae7b79ff-bbec-4c93-8c55-26f39374708b)
<hr>

### 1. My first suggestion is to add separate theme palettes (I know they are the same colors now, it's just an example):
```.json
// dark theme palette
"indentRainbow.colors.dark": [
        "rgba(255, 255, 60, 0.2)",
        "rgba(255, 60, 255, 0.2)",
        "rgba(20, 165, 255, 0.2)",
    ],
// light theme palette
"indentRainbow.colors.light": [
        "rgba(255, 255, 60, 0.2)",
        "rgba(255, 60, 255, 0.2)",
        "rgba(20, 165, 255, 0.2)",
    ],
```
This would be great, because I would also like to reduce the transparency in the light theme.
<hr>

### 2. My second suggestion is to support what I want, in the extension as an option, as the name suggests "Bracket color mode", as the color sequence isn't always perfect, here is an example:
![image](https://github.com/user-attachments/assets/1e833350-cac4-4df4-b6b9-34d501a91763)

I really don't know how this can be achieved, but I believe it's possible, maybe by detecting the closest bracket color to the indentation or something? also it would be great if it matches html elements, maybe with the color grey? or just make the color customizable!

**Comment by oderwat** [comment]
I am not going to include bracket coloring and think that you should pick either dark or light theme and stick to that.

**Comment by Alyaqdhans** [comment]
> you should pick either dark or light theme and stick to that.

The problem is, it depends on the room I'm in, I switch very often between dark/light themes, it will be very annoying switching the colors from the settings.json file every time for simple colors on the side.

**Comment by Alyaqdhans** [comment]
If anyone wondering, I found an extension that does the exact same thing I wanted
**Toggle Bracket Guides**:
https://marketplace.visualstudio.com/items?itemName=TGOSystems.togglebracketguides
