### ISSUE TITLE
How to turn off this error reminder?

### ISSUE THREAD

**Issue by ChinaGodMan** [oderwat/vscode-indent-rainbow#188]
My indentation is wrong
How to turn off this error reminder?

![Snipaste_2024-10-20_10-16-25](https://github.com/user-attachments/assets/9dfa5a3d-3c5c-4d14-9ab7-aac794efff0f)

**Comment by oderwat** [comment]
You could start with reading the documentation: https://github.com/oderwat/vscode-indent-rainbow?tab=readme-ov-file#hiding-error-highlighting

**Comment by ChinaGodMan** [comment]
> You could start with reading the documentation: [oderwat/vscode-indent-rainbow#hiding-error-highlighting](https://github.com/oderwat/vscode-indent-rainbow?tab=readme-ov-file#hiding-error-highlighting)您可以从阅读文档开始：

I used this yesterday, but it didn't work. Maybe I didn't use it correctly. I'll try again. Thank you for your response. 🙂
