### ISSUE TITLE
FEATURE REQUEST: Indent only specific blocks in .vue files

### ISSUE THREAD

**Issue by mmouhib** [oderwat/vscode-indent-rainbow#190]
Currently, the indentation in .vue files applies uniformly to all blocks. It would be highly beneficial to have a feature that allows developers to indent only specific blocks (e.g., `<script>`, `<template>`, `<style>` blocks) within .vue files. This feature would improve code readability and maintain consistency across larger codebases.

**Comment by oderwat** [comment]
I do not understand this request. This plugin does not change your indentation.

**Comment by mmouhib** [comment]
What I meant is to have only specific blocks of a file with the rainbow indent on it, like in .vue files, to only have the block <template> with the feature on. it's like adding vue.template or vue.style in the included languages instead of only vue in the included language in the extension's settings

**Comment by oderwat** [comment]
The plugin has no grammar information (blocks) which would make this possible. To implement something like this the plugin would need a global understanding of the file. This is impossible with the current implementation that basically just looks at single lines. I think it is by far out of the scope of such a plugin to do this. But maybe somebody else has an idea on how to solve that.
