### ISSUE TITLE
Light theme support

### ISSUE THREAD

**Issue by wmertens** [oderwat/vscode-indent-rainbow#2]
Hi, would it be possible to color the indents depending on the body background color?

If you have a light theme it looks a bit weird…

![image](https://cloud.githubusercontent.com/assets/54934/14887460/422e074c-0d56-11e6-9a3b-02aaff4ed116.png)

**Comment by oderwat** [comment]
I am going to check out whats possible. One way would be that one could define the colors in the config.

**Comment by oderwat** [comment]
You may create what you want by changing the new configurable colors in a way that it matches your taste! Have fun!

**Comment by rakkarage** [comment]
but I think we need two settings cuz looks fine in dark... only wanna change light

**Comment by skalinets** [comment]
I just reduced the alpha channel (it's actually a transparency), looks not bad. Especially with used together with https://github.com/CoenraadS/Bracket-Pair-Colorizer-2. 

![image](https://user-images.githubusercontent.com/822748/49455137-4fa11000-f7ef-11e8-88cf-abb4836a1a50.png)

**Comment by MarshallOfSound** [comment]
Anyone looking for light theme colors this works well~ish

```json
[
  "rgba(200,200,16,0.3)",
  "rgba(32,200,32,0.3)",
  "rgba(200,32,200,0.3)",
  "rgba(16,140,140,0.3)"
]
```

**Comment by heygambo** [comment]
For everyone who likes it a little bit more subtle:
```
[
  "rgba(200,200,16,0.03)",
  "rgba(32,200,32,0.03)",
  "rgba(200,32,200,0.03)",
  "rgba(16,140,140,0.03)"
]
```

**Comment by MatheusRich** [comment]
I needed something minimalistic (i.e., monochromatic) that worked in both light and dark mode. This is how it looks on Night Owl Light (light) and One Dark Pro (dark):

<img width="590" alt="image" src="https://github.com/oderwat/vscode-indent-rainbow/assets/20938712/126765d1-d403-4208-9102-2b86188a8969">

<img width="604" alt="image" src="https://github.com/oderwat/vscode-indent-rainbow/assets/20938712/1424daec-96c1-4341-916f-2a433409bc9e">



The config:

```json
[
  "rgba(100, 116, 139, 0.175)",
  "rgba(100, 116, 139, 0.1)",
  "rgba(100, 116, 139, 0.025)"
]
```
