### ISSUE TITLE
Pull colors from color theme

### ISSUE THREAD

**Issue by curtisblackwell** [oderwat/vscode-indent-rainbow#20]
This plugin has been super helpful, it's way quicker to find where blocks open/start with this than it is with just thin vertical lines of the same color. Thanks for building/sharing!

I change my theme fairly frequently, b/c it helps me get a fresh look at my code. It would be great if Indent Rainbow could pull from the theme's colors so that it matches. As it is now, I find it a little distracting.

**Comment by oderwat** [comment]
This is nothing I am going to work on. I actually also would not change my color scheme because it would blur my look at the code ;-)
