### ISSUE TITLE
Can we have an option to colour the indent lines

### ISSUE THREAD

**Issue by fwzmhmd** [oderwat/vscode-indent-rainbow#21]
Great little tweak. Can we have it so that it only colours the indent lines and not the whole block.

Something similar to the image below.

![Imgur](https://i.imgur.com/Np51NZp.jpg)

**Comment by GeraldNDA** [comment]
as an option maybe?

**Comment by oderwat** [comment]
I fear not. As this is not how it works. I know of no way to render a line in the free area in front of the text without adding "text". It currently works by setting the background color of the "spaces" in front of the line. For those kind of vertical lines the developers would need to support it.
