### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by michaelwnelson** [oderwat/vscode-indent-rainbow#22]
Public repositories on GitHub are often used to share open source software. For your repository to truly be open source, you'll need to license it so that others are free to use, change, and distribute the software.

Refer to the following URL to read about how to determine a license that is appropriate for this application and how to apply it.

https://help.github.com/articles/licensing-a-repository/

**Comment by oderwat** [comment]
Oh.. Strange that I forgot to add a license here. Thanks for the heads up!
