### ISSUE TITLE
indent errors

### ISSUE THREAD

**Issue by rakkarage** [oderwat/vscode-indent-rainbow#27]
under a couple of circumstances I get the indent error when maybe I should not

![2018-10-06 6](https://user-images.githubusercontent.com/962340/46575083-aa97c180-c97c-11e8-801b-0716c2f2328d.png)

c# linq is formatted differently by default by vscode and shows as an error
even when 'fixed' it just reverts to this indent when saved or formatted
maybe this could be detected and bypassed somehow or

![2018-10-06 8](https://user-images.githubusercontent.com/962340/46575105-ed599980-c97c-11e8-8e08-f2354560ac49.png)

markdown must use 2 spaces for indentation I think otherwise markdown lint will flag it as error
so even tho I use tab4 normally and in settings I still must use space2 for *.md
I guess if I used space2 for everything I would not notice this but maybe possible not to use settings on md files and instead check for 2 spaces like markdown lint does?

thanks!

**Comment by oderwat** [comment]
The error lines are just what is supposed to happen. This is per definition an error. You could define a "match all lines" as ignore line pattern if you don't want to see these kind of highlighting. There is no way for the plugin to "know the rules" a special language / linter has.

The second example seems to use another tab size than two while then using indentations of two spaces for real. Therefor this is also an expected error. As said above you may want to disable error highlighting completely. But I think you should consider to switch the indentation based on file types.

**Comment by rakkarage** [comment]
i like and enjoy the error highlighting and want to be notified of indent errors because it is helpful
these are two examples of non-errors that cannot be simply fixed i guess
thanks

**Comment by rakkarage** [comment]
so you read the tab size from settings but cannot just infer it from file type? *.md?
thanks

**Comment by oderwat** [comment]
Or use: https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig as "many of us do" :)

**Comment by rakkarage** [comment]
It may be out of scope the set or setup filetypes... but is out of scope to get filetype?
The editor recognizes and selects Markdown without any configuration changes or extensions
since we know it is markdown and since markdown uses 2 spaces could that not be an error?

**Comment by oderwat** [comment]
Validating style or syntax should not be done by this plugin. The error line is optional and in retrospective probably even a bad idea.

**Comment by zc62** [comment]
For the markdown 2 spaces indent issue, why isn't using settings for md an option?
```json
"[markdown]": {
    "editor.tabSize": 2
}
```
in `settings.json` works nicely.
