### ISSUE TITLE
Request: Display rainbow across empty lines

### ISSUE THREAD

**Issue by GeoffreyEmerson** [oderwat/vscode-indent-rainbow#28]
Our code style often breaks up sections with an empty line, which will have zero tabs or spaces, while the line before and after will have matching tabs or spaces. The break in the rainbow is distracting. Is there a current way to make the rainbow show up despite having zero tabs on the line? I only need it on empty lines where the indenting on the line before and after match.

**Comment by JoelMacKenzie** [comment]
I'd also like to see blank lines filled in.  The breaks in the rainbow don't look nice at all in my opinion.  Too bad it's not possible. 

![image](https://user-images.githubusercontent.com/5419006/55162961-a6887780-5147-11e9-84d9-dadf128741fb.png)

**Comment by oderwat** [comment]
Well. Even if it where possible I would probably not implement it, because I want the plugin to reflect the whitespace situation. I would think that I need to remove whitespace in empty lines otherwise.

**Comment by godsey** [comment]
> Well. Even if it where possible I would probably not implement it, because I want the plugin to reflect the whitespace situation. I would think that I need to remove whitespace in empty lines otherwise.

This makes sense for Python, but what about Go and C which are bracketed?

**Comment by oderwat** [comment]
> This makes sense for Python, but what about Go and C which are bracketed?

Wenn the plugin was originally designed by myself for Nim-Lang which is kinda in the same boat as Python. Now I actually use it more for Python and Haskell though. Still it does not make sense to me (besides of maybe aesthetics) to colorise empty lines. Thats independent of the language.

BTW: What should be the "right" colorisation for line 463 anyway? Is there one "tab" or are there two "tabs" to indicate. Technically there would be only one without "looking into the future". But what if line 464 is defective? It would only ever be "correct" when you are running real linter / formatter with some logic for whats being considered correct.

But all of this is mood as it is not possible to implement afais anyway.

**Comment by Diogo-Rossi** [comment]
I'd also like to see blank lines filled in.

If it was possible to identify the "indentation line" in each blank line . . .
maybe it could fill with colors "until one tab after the last indentation line"?

I mean, I'd like to see something like this: (without the need to add white tab spaces in every line)

![image](https://user-images.githubusercontent.com/57204023/81242622-ff317180-8fe3-11ea-8bb6-11dfbf4cc1ee.png)

Too bad it's not possible. But it is still a great plugin. Good job.

**Comment by oderwat** [comment]
Even if it were possible I would not agree with line 39 having more indentation than line 38.  So this would need to be configurable too. It also would make the process slower.

Sorry but there seems not to be a happy end for such a feature.

P.S.: Having 800.000+ installs with zero donations does not make me happy either.

**Comment by niktor76** [comment]
we need this

**Comment by oderwat** [comment]
It is not possible! But if you find a magic solution, send me a PR.
