### ISSUE TITLE
continue indentation on blank line

### ISSUE THREAD

**Issue by wmertens** [oderwat/vscode-indent-rainbow#3]
Is it possible to paint blank lines to the indentation level of the last non-blank line?

That way, blocks with blank lines in them still look like a coherent whole.

**Comment by oderwat** [comment]
I fear thats not possible without adding whitespace into those lines. The whole thing is basically a crazy hack which colorizes the contents of the file. Adding whitespace and colorize it would probably work but changes the contents in those lines and would need to be removed on save (which is the default for my setup). I actually think that the blank line is fine as it shows that no whitespace is there.

**Comment by wmertens** [comment]
Ok fair enough, I suppose that is a shortcoming in vscode…

**Comment by oderwat** [comment]
Yes.. btw.. I got inspired by your textblade karabiner profile for my [neo2](https://github.com/oderwat/karabiner) (german special layout) profile which uses multiple layers. I just recognized that we both are in the waytools forum 👍

**Comment by Jarrio** [comment]
I was wondering if this issue can be reopened based on how far vscode has come since this issue was initially made
![image](https://user-images.githubusercontent.com/748557/61188109-5d1a5480-a672-11e9-924f-74cbb6b4c254.png)

**Comment by oderwat** [comment]
Nope.. still needs "something" to colorise it.

**Comment by viliwonka** [comment]
"editor.trimAutoWhitespace": false,
"editor.renderWhitespace": "all"

May help with the issue (but not for existing files)

**Comment by cptSwing** [comment]
^lovely, seems to work for me

**Comment by DanTup** [comment]
I know this issue is quite old, but FWIW I have a need for similar APIs and opened an issue in VS Code here:

https://github.com/microsoft/vscode/issues/73780

It has 300 👍 's, but there doesn't seem to have been any activity on it. Additional 👍 's to show that there's demand that might make it worth adding new APIs might help :-)
