### ISSUE TITLE
[Feature request] Treat mixing tabs and spaces as error.

### ISSUE THREAD

**Issue by kvinwang** [oderwat/vscode-indent-rainbow#31]

**Comment by kvinwang** [comment]
> Is [this one](https://github.com/oderwat/vscode-indent-rainbow/pull/39) what you want?

This is exactly what I want. Thanks very much.

**Comment by wraith13** [comment]
You are welcome!

**Comment by oderwat** [comment]
This will be removed together with all kinds of "error" marking. This should be done with some linter style program. Adding it to the scope of the plugin was an error.
