### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by soewarsono** [oderwat/vscode-indent-rainbow#33]
- Issue Type: `Performance`
- Extension Name: `indent-rainbow`
- Extension Version: `7.2.4`
- OS Version: `Linux x64 4.18.0-parrot20-amd64`
- VSCode version: `1.30.0`

:warning: Make sure to **attach** this file from your *home*-directory: `/home/soewarsono/oderwat.indent-rainbow-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by Box-Of-Hats** [comment]
I'm having input latency issues when using indent-rainbow with a large (20k+ line) XML file.
Performance in other files seems to be acceptable, however

**Comment by oderwat** [comment]
The only fix I may offer (when I got time to work in it) is that it disables itself when processing lasts longer than some time X. Working / testing for other (maybe impossible) optimisations is not on my agenda anytime soon.
