### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by AlejandroMataGuillen** [oderwat/vscode-indent-rainbow#34]
- Issue Type: `Performance`
- Extension Name: `indent-rainbow`
- Extension Version: `7.2.4`
- OS Version: `Linux x64 4.15.0-42-generic`
- VSCode version: `1.30.1`

:warning: Make sure to **attach** this file from your *home*-directory: `/home/alejandro/oderwat.indent-rainbow-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by oderwat** [comment]
You forgot to attach the file. But there is also the question what file(s) caused this and if it can be reproduced. I also can't check /debug this on any other hardware than Macs, because I won't use other computers.

**Comment by dc-avasilev** [comment]
> You forgot to attach the file. But there is also the question what file(s) caused this and if it can be reproduced. I also can't check /debug this on any other hardware than Macs, because I won't use other computers.

https://github.com/oderwat/vscode-indent-rainbow/issues/35
