### ISSUE TITLE
Wrong detection tabs

### ISSUE THREAD

**Issue by sartyukhov** [oderwat/vscode-indent-rainbow#38]
If line have '*' in it (pointer in C for example), extension colorise it wrong.

```c
void My_Function_Name(var_0_t var_0
                      var_1_t * var_1)
```

**Comment by oderwat** [comment]
Please define "wrong". I don't see anything wrong when I use your example? Maybe create a screenshot for visualisation of the problem.

**Comment by oderwat** [comment]
You may using the "errorColor" for lines which are not a multiple of tabsize together with the example "supression" pattern for lines starting with `*`. This would be a configuration problem. Besides that, I basically dropped any support for the "error" feature as what is an error or not should be evalued by a lint style type of tool. It is much to complicated to implement without parsing and that is outside of the scope of the plugin.

**Comment by sartyukhov** [comment]
![image](https://user-images.githubusercontent.com/23495999/51189776-c6065700-18f1-11e9-9258-eaffb509e89b.png)
Look at "var_1_t", first 2 characters are colored green.
In vscode activated "Indent using spaces: 4"

**Comment by sartyukhov** [comment]
Ok, up to you.
