### ISSUE TITLE
wrong / broken indent detection

### ISSUE THREAD

**Issue by Morgy93** [oderwat/vscode-indent-rainbow#45]
Hello,

I came across some weird error:

![image](https://user-images.githubusercontent.com/7961978/52974563-4ffa8180-33c2-11e9-8305-7d3f3feef871.png)

This is from the vscode settings.json

```
{
  "editor.renderWhitespace": "boundary",
  "editor.wordSeparators": "`~!@#%^&*()-=+[{]}\\|;:'\",.<>/?",
}
```

This is due to the `*` in the `editor.wordSeparators` setting. If I remove the `*` it works:

![image](https://user-images.githubusercontent.com/7961978/52974663-a5369300-33c2-11e9-859d-40de071464a7.png)

**Comment by oderwat** [comment]
I will remove the error detection soon.
