### ISSUE TITLE
Disable all errors

### ISSUE THREAD

**Issue by rakkarage** [oderwat/vscode-indent-rainbow#49]
![untitled](https://user-images.githubusercontent.com/962340/53770585-9f09e180-3ead-11e9-9c50-544b94ea8492.png)

thanks for the great addon
any way to disable **all** errors? they show in addon output too? so cannot disable with ignoreErrorLanguages?
thanks

**Comment by oderwat** [comment]
I will remove the "error" markers soon.

P.S.: I thought that those output may have the type "plaintext" which would explain that I never saw this happening (as I have it off for plaintext).

**Comment by oderwat** [comment]
You should be able to disable all errors with

```
"indentRainbow.excludedLanguages": ["*"]
```

**Comment by rakkarage** [comment]
"indentRainbow.ignoreErrorLanguages": ["*"]
