### ISSUE TITLE
Breaks VS Code's built-in indentation detection

### ISSUE THREAD

**Issue by ThubLives** [oderwat/vscode-indent-rainbow#5]
- indent-rainbow version:  0.3.2
- VSCode version:  1.1.0
- OS Version:  Win7 SP1 x64

How to reproduce:
1. Make sure option editor.detectIndentation is set to true and editor.tabSize is set to 4.
2. Open a text file with 2, 6, or 8 space indentation.  Notice the status bar reports "Spaces: 4" rather than the detected indentation size.
3. Select the "Detect Indentation from Content" action.  Notice the status bar now reports the correct indentation size.
4. Type any text into the file.  Notice the status bar has returned to "Spaces: 4".

**Comment by oderwat** [comment]
It should not do anything if you have not setup an `indentRainbow.indentSetter` config and if you have setup something it is expected tot override other indent configs. Cause thats the feature exactly supposed to do. As mentioned in the ReadMe this feature by itself is considered buggy. It works for my use case though.

**Comment by ThubLives** [comment]
The intended behaviour is unclear, both in the readme and in your comment here.
My interpretation after reading the readme again is that "The following is experimental and still buggy (do not use it :)" means I should not add any of the following to my configuration and it will fall back to native VS Code indent setting behaviour.
Should I be adding the line
`"indentRainbow.indentSetter": {} // do nothing as default`
to allow native behaviour or does the "do nothing as default" comment mean that it will block the native detection behaviour?

**Comment by oderwat** [comment]
It should work without that extra line and if you do not add anything else. My code is supposed to do nothing in that case but it seems that there is a problem with that! Investigating right now!

**Comment by oderwat** [comment]
This should be fixed by 3efd5d534ba466679b7e7c8c1b031359e66a6962 and is 0.4.0 (published) now! Thank you for reporting this. I guess the auto detection of indentation is most of the time what anybody wants for default.

Please report if it is working for you know!

**Comment by ThubLives** [comment]
0.4.0 is working great for me with no config settings.  Thanks for looking into this!

**Comment by oderwat** [comment]
Good! Thank you for taking your time to report the problem. Have fun!
