### ISSUE TITLE
`indentRainbow.ignoreLinePatterns` doesn't really ignore what it matches.

### ISSUE THREAD

**Issue by lizebang** [oderwat/vscode-indent-rainbow#54]
I add `"/\\/\\*[\\w\\W]*?\\*\\//g"` to the `indentRainbow.ignoreLinePatterns` and it can match multi-line annotations. But indentRainbow doesn't really ignore what it matches and inferes the format from the multi-line comments. Because the comments are at the top of the file.

![Screen Shot 2019-03-18 at 12 18 41 PM](https://user-images.githubusercontent.com/26663453/54506734-df229700-4978-11e9-99cd-e63e7dfe08b9.png)

**Comment by oderwat** [comment]
I believe this is the same problem as in #52.

**Comment by oderwat** [comment]
I released an update of the plugin which also has some new defaults. Please try this!
