### ISSUE TITLE
Configure extension ?

### ISSUE THREAD

**Issue by SheepDomination** [oderwat/vscode-indent-rainbow#55]
Where do you configure *indent-rainbow*; the `settings.json` file doesn't recognize any of this extensions settings ?

**Comment by oderwat** [comment]
That is strange. They should work and do for me in the same way as any other extension settings.

**Comment by SheepDomination** [comment]
When editing or modifying the `settings.json` file, and I begin typing; `"indent~~~` in your case an intellisense notification list occurs, correct ?
If so, that doesn't show on my end, rather an error because code doesn't know how to recognize the setting.

**Comment by SheepDomination** [comment]
I solve the problem, silly me forgot to move the closing brace `}` out of my comments area.
