### ISSUE TITLE
Mismatch between Prettier and indent-rainbow logic

### ISSUE THREAD

**Issue by Moeriki** [oderwat/vscode-indent-rainbow#56]
There seems to be a disconnect between the logic applied by Prettier and indent rainbow.

<img width="195" alt="image" src="https://user-images.githubusercontent.com/38758/59277150-f4e5e680-8c5f-11e9-8de5-c23e92f96899.png">

In a multi-line object in a multi-line ternary Prettier will start counting its desired indentation starting from the `{`, where `indent-rainbow` counts from the default multiple of 4 spaces.

I understand why both Prettier and `indent-rainbow` do what they do.

I also understand there is probably little you can do about this.

For people looking for the same issue, I worked around the issue with this setting.

```js
{
  "indentRainbow.errorColor": "rgba(0,0,0,0)",
}
```

This is better, though not ideal either, as it hides the default indent colors.

Would it be possible to add an option to disable the `errorColor`? A possible fallback would be to colorize the indentation as usual (per multiple of 4 spaces) and not colorize the last 2 erroneous spaces.

**Comment by oderwat** [comment]
Indent Rainbow makes no assumptions about what is "pretty". Just disable error markers for the language or altogether, like so:

```
"indentRainbow.ignoreErrorLanguages" : [ "*" ]
```

**Comment by Moeriki** [comment]
Nice `ignoreErrorLanguages` is perfect for my needs.

**Comment by gbrunow** [comment]
There is a slightly annoying thing ignoring errors that it doesn't solve though, the highlight behind the first two characters.

![image](https://user-images.githubusercontent.com/5505621/88444897-1dd62600-cde5-11ea-92a9-f6a0dc06c984.png)

**Comment by oderwat** [comment]
That doesn't annoy me as I would not have such kind of indent in my projects. But I guess I would accept a PR for an optional behavior if it doesn't degrade performance too much.

**Comment by gbrunow** [comment]
Personally I don't like that indentation either, but prettier is opinionated and won't let me change that, believe me, I tried.
I will take a look at the code and see if I can submit a PR request when I have time.

**Comment by gbrunow** [comment]
I'm currently working on this and will probably submit other changes if that's okay with you.
I'm submitting a simple one in a few minutes just so it's not too much at once.

**Comment by oderwat** [comment]
After some more thinking about it, I decided that the current behavior is what I want. Resizing the bars to "fit" the code in the last example just looks wrong to me. Change the tab size to two if you write code in this style. You very obviously don't use an indentation of four spaces there.

**Comment by gbrunow** [comment]
It is 4 spaces but prettier isn't consistent when indenting chained methods.
This is what it looks with 2 spaces:

![image](https://user-images.githubusercontent.com/5505621/88485509-dca45a00-cf3b-11ea-8e01-826d17b87026.png)

**Comment by keidarcy** [comment]
Does anyone know what's logic how rainbow-indent decides the space(2 or 4)?

**Comment by oderwat** [comment]
It uses what the editor uses. So it is either a "tab size" or count of "spaces". You can see that in the bottom status bar of the editor window.
