### ISSUE TITLE
does not colorize lines where text is wrapped

### ISSUE THREAD

**Issue by rod007vrr** [oderwat/vscode-indent-rainbow#57]
when I turn on text wrapping for lines the indented space created is not colored
![Screen Shot 2019-06-19 at 4 46 48 PM](https://user-images.githubusercontent.com/37837157/59799194-d9a75680-92b1-11e9-98a0-a2ef0e544e20.png)

**Comment by oderwat** [comment]
Sorry but this can not be fixed (and should not as the line ist noch indented for real)
