### ISSUE TITLE
Feature Request: use background instead of backgroundColor

### ISSUE THREAD

**Issue by walston** [oderwat/vscode-indent-rainbow#58]
I wanted to use a gradient background to fade from solid to transparent, but since you're using `backgroundColor` it does not accept gradients.

Would it be possible to switch to using just `background`?

**Comment by ijoel92** [comment]
You can change the transparency in the rgba formula

"indentRainbow.colors": [
        "rgba(127,255,127,0.6)",
        "rgba(127,255,127,0.4)",
        "rgba(127,255,127,0.25)",
        "rgba(127,255,127,0.15)"
]

**Comment by gbrunow** [comment]
@walston That would actually be great! However, I just check and the `vscode` API doesn't allow that.
This issue could be closed.
