### ISSUE TITLE
Expose indent bars to theming

### ISSUE THREAD

**Issue by Zireael** [oderwat/vscode-indent-rainbow#59]
Hi,
Can't see your internal code workings for generating indent bars, but hopefully that involves some CSS. And here comes my thought whether you could add an option of providing entire CSS class for each indent bar.
I would use that to create colors with gradients rather than monocolor. For example, in Atom, I created the following indent bars with a bit of CSS using a similar extension to yours:
https://atom.io/packages/indent-guide-improved

![image](https://user-images.githubusercontent.com/3856578/62832514-8e615280-bc27-11e9-8cba-88a3ca662326.png)

Maybe it's a bit hard to see on small pic but I'd like to be able to make the indents less in my face (more thinner line and gradiented) rather than solid blocks of color.

I'm generating the indent line colors dynamically in Atom like so (in .less)
```
  .color-guides(20);

  .color-guides(@total, @i:1) when (@i <= @total) {
    .indent-guide-stack:nth-child(@{total}n + @{i}) {

      background: repeating-linear-gradient(
        to bottom,
        rgba(158, 158, 158, 0.01),
        rgba(0, 0, 0, 0) 1px
      );
      @indent-col: rgba(
        mod(@i * 20 + 50, 150),
        mod(@i * 2 + 50, 150),
        mod(@i * 100 + 50, 150),
        @i*0.045
      );
      box-shadow: inset 1px 0 @indent-col;

      &.indent-guide-active {
        background: repeating-linear-gradient(
          to bottom,
          rgb(1, 162, 226),
          rgb(1, 162, 226) 100%
        );
      }
      background: repeating-linear-gradient(
        to bottom,
        rgba(158, 158, 158, 0.75),
        rgba(0, 0, 0, 0) 20%,
        rgba(0, 0, 0, 0) 80%,
        rgba(158, 158, 158, 0.75) 100%
      );
    }
    .color-guides(@total, (@i + 1));
  }
```

And here is my color theme for vscode-indent-rainbow
Color theme: _Dracula at night_
```
    "indentRainbow.colors": [
      "rgba(6, 77, 105,0.4)",
      "rgba(123, 166, 184,0.3)",
      "rgba(109, 150, 105,0.4)",
      "rgba(242, 210, 127,0.2)",
      "rgba(255,255,64,0.07)",
      "rgba(127,255,127,0.07)",
      "rgba(255,127,255,0.07)",
      "rgba(79,236,236,0.07)"
  ]
```

![image](https://user-images.githubusercontent.com/3856578/62832619-08dea200-bc29-11e9-9c0a-70ee7e61fe12.png)

Lastly, would it be possible to add toggle for showing Error Color? I have ESlint to nag me about that and big distracting blocks of red weren't that helpful. For now I've just set opacity of the color to pretty much nothing:
`"indentRainbow.errorColor": "rgba(128,32,32,0.005)"`

Thanks for making the extension!

**Comment by oderwat** [comment]
Sorry but there is no css involved. Also there is already a setting to disable "error" highlighting by disabling it for all languages.
