### ISSUE TITLE
After last update, ident rainbow doesn't work

### ISSUE THREAD

**Issue by gricelsepulveda** [oderwat/vscode-indent-rainbow#61]
When you open vs code, all looks fine at the first time, but few click later ident rainbows are hidden

<img width="2694" alt="Screen Shot 2019-08-20 at 6 15 27 PM" src="https://user-images.githubusercontent.com/12860968/63446655-97f97000-c408-11e9-8f5f-bc31417347cd.png">
<img width="1191" alt="Screen Shot 2019-08-21 at 11 37 13 AM" src="https://user-images.githubusercontent.com/12860968/63446657-97f97000-c408-11e9-9b60-8306b4708be5.png">

vscode version:
Version: 1.37.0
Commit: 036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8
Date: 2019-08-08T01:22:37.660Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.7.0

**Comment by oderwat** [comment]
I can't confirm any problems. Please try the newest vscode!

```
Version: 1.37.1
Commit: f06011ac164ae4dc8e753a3fe7f9549844d15e35
Datum: 2019-08-15T16:16:34.800Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
Betriebssystem: Darwin x64 18.7.0
```
