### ISSUE TITLE
The Explorer desperately needs this!!

### ISSUE THREAD

**Issue by yamlCase** [oderwat/vscode-indent-rainbow#63]
I just found indent rainbow as a solution to a problem I didn't know I had... but man was it a big problem!  Now I can't stop seeing how the side explorer needs this as well.  Is this even a possibility in VSCode?

**Comment by KayodeOgidan** [comment]
here is what you need:

{
   "tree.indentGuidesStroke": "#ff0000",
  "workbench.tree.indent": 20,
  "workbench.tree.renderIndentGuides": "always",
}
