### ISSUE TITLE
Empty lines in an indented section should be colored

### ISSUE THREAD

**Issue by Tyriar** [oderwat/vscode-indent-rainbow#7]
Not sure if it's possible but it would be ideal if these lines were colored as well:

![image](https://cloud.githubusercontent.com/assets/2193314/15347696/e1bf10c2-1c78-11e6-8aeb-f7500589916f.png)

**Comment by Tyriar** [comment]
Looks like it's not possible atm. https://github.com/spywhere/vscode-guides/issues/1

**Comment by oderwat** [comment]
Yes.. we had this here before too: https://github.com/oderwat/vscode-indent-rainbow/issues/3
