### ISSUE TITLE
Python : Indentation is proper but indent rainbow is showing it as error

### ISSUE THREAD

**Issue by KumarswamyS** [oderwat/vscode-indent-rainbow#70]
I have a print statement in python which is of two lines, indent rainbow is improperly showing the second line of the print statement as indentation error.

<pre><code>print("\033[92m"+"{0:.2f}".format(monthlyRet[0]*100),
      "{0:.2f}".format(bimonthlyRet[0]*100)+"\033[00m")</code></pre>   
Second line of print statement is improperly indentented accoring to indent rainbow

**Comment by oderwat** [comment]
It is... according to the rules. Just switch it off and use a lint tool if you want to have language agnostic indentation error tests.

**Comment by Exploder98** [comment]
@oderwat What rules are you referring to? According to PEP8 (Python style guide), continuation indents [should be aligned with the opening delimiter](https://www.python.org/dev/peps/pep-0008/#id17). I can of course set the error color to be completely transparent, but that kind of destroys its idea.

**Comment by oderwat** [comment]
The rules from the settings?

An error is by definition:
> if the number of spaces is not a multiple of "tabSize".

This is no linter and could care less about Python style guides! 

I would suggest, that you use a linter for checking your Python code style and disable errors in indent-rainbow as they are obviously not what you expect them to be.
