### ISSUE TITLE
[Feature Request] show indent guide for empty lines

### ISSUE THREAD

**Issue by japamat** [oderwat/vscode-indent-rainbow#71]
Is there a way to add the correct indent guide to empty lines, e.g. 

for the following:
```javascript
function sumDoubleNums(a, b) {
  const aDoubled = a * 2;
  const bDoubled = b * 2;

  return aDoubled + bDoubled
}
```
Any way the line between declaring `bDoubled` and the return statement to have an indent guide? Some way to tell that if the line has no spaces nor tabs, treat it as if it held the same number of tabs or spaces as the line above?

I've tried digging around in the `extension.ts` file and can't for the life of me figure out where it's evaluating the content for either tabs or spaces.

**Comment by oderwat** [comment]
See #3 ... sorry!
