### ISSUE TITLE
Only indent after a certain level

### ISSUE THREAD

**Issue by qortex** [oderwat/vscode-indent-rainbow#73]
Indenting from first level puts a solid bar on the left of the whole code, since lines are usually at least one-level nested (class, whatever).

For now, I use transparent colors for first levels instead and repeat them to avoid cycling through the transparent ones, which does the trick:
```json
"indentRainbow.colors": [
    "rgba(255,255,64,0)",
    "rgba(127,255,127,0)",
    "rgba(255,255,64,0.07)",
    "rgba(127,255,127,0.07)",
    "rgba(255,127,255,0.07)",
    "rgba(79,236,236,0.07)",
    "rgba(255,255,64,0.07)",
    "rgba(127,255,127,0.07)",
    "rgba(255,127,255,0.07)",
    "rgba(79,236,236,0.07)",
    "rgba(255,255,64,0.07)",
    "rgba(127,255,127,0.07)",
    "rgba(255,127,255,0.07)",
    "rgba(79,236,236,0.07)",
    "rgba(255,255,64,0.07)",
    "rgba(127,255,127,0.07)",
    "rgba(255,127,255,0.07)",
    "rgba(79,236,236,0.07)"
    ],
```

Would be nice to have a setting `startingLevel` instead.

**Comment by gbrunow** [comment]
I submitted a PR (#92) for this.

**Comment by oderwat** [comment]
I don't have a "solid bar on the left" as I (and anybody else?) have code which starts on column 0.

**Comment by gbrunow** [comment]
Yes, my bad, I think I may have forgotten to change the default back to 0.
However, you seem to not agree to the existence of this feature so I think I won't bother changing it.

**Comment by qortex** [comment]
> I don't have a "solid bar on the left" as I (and anybody else?) have code which starts on column 0.

Well, that's because you do not use a language where constructs such as following are customary (ruby):
```ruby
module MyModule
  module MySecondModule
    class MyClass
      # code...
    end
  end
end
```

Some people like me do. And I do not like having one big bar going from `MyModule` to `end`.

But right, you might as well ignore that fact. I'll stick with my workaround.

Thanks for the effort @gbrunow !

**Comment by oderwat** [comment]
I use languages and documents which are indented for most code. I just don't see a point in not having this modification. I also don't see why your Ruby code should omit the coloring in the first or later column. Aesthetics can't be changed by coloring as you pointed out. Having additional logic in the code just slows things down.

**Comment by gbrunow** [comment]
May look like because of the refactorings which we've discussed already.
But it's just one if statement `if (startPos.character >= minLevel * activeEditor.options.tabSize)`.
I understand if won't don't see this as being part of the extension but I don't see a performance issue here.
