### ISSUE TITLE
Feature request: Highlight only on mouse hover

### ISSUE THREAD

**Issue by yuri-scarbaci-lenio** [oderwat/vscode-indent-rainbow#74]
Is it possible to have the highlight appear only when hovering the mouse over the indents? 

The more I use the plugin the more I get frustrated by having all those color inputs come at me constantly, the feature itself is something I do love and is often time useful, but having it constantly on is somewhat of a overkill for me...

**Comment by yuri-scarbaci-lenio** [comment]
see realtish issue:
https://github.com/oderwat/vscode-indent-rainbow/issues/11

**Comment by oderwat** [comment]
I don't think that one gets "mouse over" messages. I also don't see a way for a quick "css style" switch between visible and invisible "colouring".

As this is not really a concern of me and nobody ever donated anything for this project - in spite of >500.000 installs - there is a pretty low chance that I find time to research and implent features I don't need myself. Sorry for that.

**Comment by yuri-scarbaci-lenio** [comment]
Totally legit, no need to excuse yourself, actually thank you for sharing this at all.

Good luck in the future for the donations!

I think this issue can be closed then.

**Comment by oderwat** [comment]
Thank you.. maybe I find some time in the summer. I am currently stressed out with my dayjob and usually like to help people out. So yeah.. take care.
