### ISSUE TITLE
Is it possible to show indent colors inside of a jsdoc string?

### ISSUE THREAD

**Issue by Lomomn** [oderwat/vscode-indent-rainbow#75]
![1582396475](https://user-images.githubusercontent.com/8727952/75097389-2d391500-55a2-11ea-8488-e3e13e98d452.png)

As you can see, this would be a lot more readable if the indentation worked inside. Am I missing a setting or is jsdoc not supported?

**Comment by oderwat** [comment]
It is and everything works as intended. I guess you overlook that there is a asterix in column 2 of every line.
