### ISSUE TITLE
[Feature Request] Color Only the indentation guidelines. 

### ISSUE THREAD

**Issue by Santosh-Gupta** [oderwat/vscode-indent-rainbow#76]
while the colorization of the empty space is very effective at times when you're trying to comprehend code geography, at times when you're Not trying to comprehend code geography, it gets distracting. We can put more subtle coloring or use alternating dark/light grays, but that takes away from the geography comprehension. 

I think just coloring the indentation guidelines would be a good to get the best of both worlds. With only the lines being colored, there's only a fraction of the space that is colored, and that doesn't distract from the code. But the line colors are also apparent enough that they are prominent when your focus shifts to them, when you are trying to comprehend code geography.

**Comment by oderwat** [comment]
Afaik we can't color those lines. I also would not like this behaviour personally. If somebody comes up a PR with that functionality I may include it.

**Comment by ScottGuthart** [comment]
I would also be interested in this feature. Panic's new [Nova](https://www.nova.app/#the_interface) editor for mac has an implementation that I like personally.
___
![](https://www.nova.app/images/en/interface/1.png)

**Comment by oderwat** [comment]
Yes, see my comment above.
