### ISSUE TITLE
Getting in Touch with the Author

### ISSUE THREAD

**Issue by msaaddev** [oderwat/vscode-indent-rainbow#77]
Hey, @oderwat! I want to get in touch with you with an amazing proposition but I couldn't find your email on your GitHub account. Can you please send me a blank email at mrsaadirfan@gmail.com so that I can get back to you. Thank you for your time. :)

**Comment by msaaddev** [comment]
I am now going to close this issue since it is not related to vscode-indent-rainbow. I hope you will see this message.

**Comment by oderwat** [comment]
I added an email to my profile. Let the spam flow :-)

**Comment by msaaddev** [comment]
Thank you! I have it now. I will email you shortly. :) You can remove it now if you want.
