### ISSUE TITLE
Rainbow indent does not work with combined indent

### ISSUE THREAD

**Issue by RadoiAndrei** [oderwat/vscode-indent-rainbow#80]
I do not use a formatter for some languages and I am working with multiple people, so the indent contains both tabs and spaces which makes the indent look like a long single colored horizontal line.
![image](https://user-images.githubusercontent.com/46427158/81909830-d278ed80-95d3-11ea-842a-60f1bf1d67c9.png)

**Comment by oderwat** [comment]
This is documented behavior:

>   // The indent color when there is a mix between spaces and tabs.
>  // To be disabled this coloring set this to an empty string.
>  "indentRainbow.tabmixColor": "rgba(128,32,96,0.6)"

Please read the documentation!
