### ISSUE TITLE
Indentation color includes text characters

### ISSUE THREAD

**Issue by habedi77** [oderwat/vscode-indent-rainbow#81]
After disabling the error color for multi line statements the indentation color includes several characters of text to make a "full" indent color.
![image](https://user-images.githubusercontent.com/12297645/82572255-55341680-9b99-11ea-91e4-a465c8a9396a.png)

**Comment by oderwat** [comment]
It works as I intended it to work.

**Comment by habedi77** [comment]
Is there an option to turn it off?

**Comment by oderwat** [comment]
No, I don't want to be able to turn it off. If you make a PR for changing that I may include it. But I won't spend any time on this plugin anymore after 850.000 installs with zero donations.
