### ISSUE TITLE
Refresh colors

### ISSUE THREAD

**Issue by josias-r** [oderwat/vscode-indent-rainbow#83]
When creating new files, VSCode won't detect the automatic indentation until you start typing some code. I work w/ prettier i.e. so my code will get formatted.

In my case, I need to reopen the file because the indentation does not refresh automatically after the file got formatted.

A quick command to refresh the colours would suffice though since I think having to watch for file-changes seems unnecessarily resource intense.

**Comment by oderwat** [comment]
I am not sure if the plugin can do anything about it. It reads the tab size (`activeEditor.options.tabSize`) every time it runs. As far as I remember the value simply didn't update, besides when the file was reloaded. I remember that some plugins also modified the behavior.

That said: If somebody gets it to work I would accept a PR. I am not likely going to work on it myself though. With atm 864,962 installs and a total of zero donations my interest in working on this plugin (besides my personal needs) comes close to zero.

**Comment by josias-r** [comment]
I see, that's unfortunate :( I have no experience w/ vs-code plugins whatsoever so I can't find the time either.

Btw, I looked at your donate button and I saw that PayPal would take almost 30% of my donation?? Is this how PayPal work w/ donations or is it a problem w/ my payment method?

**Comment by oderwat** [comment]
Paypal is a payment processor and as such takes money for its service. Which seems legit. But 30% seems a bit too much and does not match what they say:

> Short version: PayPal fees are 30 cents and 2.9% per transaction.

https://www.paypal.com/us/webapps/mpp/paypal-fees

**Comment by josias-r** [comment]
Hmm, I see, then it must have something to do with my payment method selected, I will have to check. 👍🏼
