### ISSUE TITLE
No documentation for the (potentially unintentional) "indentSetter" config parameter

### ISSUE THREAD

**Issue by justinmorrow** [oderwat/vscode-indent-rainbow#85]
I found this "indentSetter" config option via the VS Code settings UI menu, but it looks like it might not have been an intentional. On the current master branch it looks like the string `indentSetter` is only in the [package.json](https://github.com/oderwat/vscode-indent-rainbow/blob/cdcede40f09201f9a63643a64039e4df155316de/package.json).

If I'm wrong about all that though and the setting is intentional and functional, I didn't see any documentation in the [README.md](https://github.com/oderwat/vscode-indent-rainbow/blob/cdcede40f09201f9a63643a64039e4df155316de/README.md) as specified below
https://github.com/oderwat/vscode-indent-rainbow/blob/cdcede40f09201f9a63643a64039e4df155316de/package.json#L56-L60

**Comment by oderwat** [comment]
I had an experimental version with it but it never worked and I am convinced now that something like that should be part of a language server or linter per se.
