### ISSUE TITLE
Should I indent even number?

### ISSUE THREAD

**Issue by chinyajie** [oderwat/vscode-indent-rainbow#86]
Extension Version: 7.4.0
VSCode version: 1.44.2

Should I must indent even number?

![image](https://user-images.githubusercontent.com/9836595/84469912-ba6cba80-acb4-11ea-922b-54e23e7ad90b.png)
![image](https://user-images.githubusercontent.com/9836595/84470035-facc3880-acb4-11ea-886e-41729c219fa2.png)

**Comment by oderwat** [comment]
You can switch off the intent error color if you don't want to stay with your indenting rules.
