### ISSUE TITLE
Set the minimum amout of lines to start coloring

### ISSUE THREAD

**Issue by Juno72** [oderwat/vscode-indent-rainbow#87]
To reduce the amount of coloring due to indents of e.g. wrapped code, specify the minimum of amount of lines to start coloring an indent.
Maybe even better is to count of effective code lines instead of amount of screen lines. Effective code lines takes into account the empty lines and wrapped code, or wrapped comment blocks.

**Comment by gbrunow** [comment]
Do you mean like?

```
if(true){
    // do something <-- no coloring
}
```

```
if(true){
    // do something <-- coloring
    // do something <-- coloring
    // do something <-- coloring
    // do something <-- coloring
    // do something <-- coloring
    // do something <-- coloring
    // do something <-- coloring
}
```

That way only large block of code would be colored?

**Comment by oderwat** [comment]
This would defeat the purpose of the plugin, which actually is showing a representation of the indents. Maybe you need another color schema for your personal perception.
