### ISSUE TITLE
A more discrete way to highlight

### ISSUE THREAD

**Issue by josemadriz** [oderwat/vscode-indent-rainbow#9]
i was trying to get this to color a vertical line using 
vscode.window.createTextEditorDecorationType
but the API offers nothing in CSS like 
`content:'|'`
to add new characters as decorators.
Neither 
`borderLeftColor: colors[i]`
Work
So I hacked the generated JS to ad this instead of the background color 

`
decorationType[i] = vscode.window.createTextEditorDecorationType({
            color: colors[i],
            textDecoration: 'line-through'
        });
`

**Comment by oderwat** [comment]
The target of this plugin is creating rainbow colored background cells and that those only appear where whitespace is. If you want to have other types of guides or behavior I suggest that you either create a sensible PR or fork the project (or just hack it for your own usage).

You may be able to create what you originally want by following this hack: https://github.com/Microsoft/vscode/issues/6201
