### ISSUE TITLE
PHP Laravel Blade

### ISSUE THREAD

**Issue by imomer** [oderwat/vscode-indent-rainbow#95]
Indent rainbow acting weird when I'm in PHP laravel blade template. But is works in JSX for me

[Screenshot here](https://prnt.sc/uomyfq). 

I'm using prettier extension with it...

**Comment by oderwat** [comment]
What do you mean with it acting weird? I don't see a problem besides that the right editor window seems to have a 2 space indent rule set in VSCode which does not reflect what the code actually seems to use. As there is no status bar in the screen shoots one can't tell for sure what's going on though.

**Comment by imomer** [comment]
The spaces are set to 4 everywhere. But turns out it was a problem with HTML in PHP format extension.
