### ISSUE TITLE
yaml indentation highlighting

### ISSUE THREAD

**Issue by koekaverna** [oderwat/vscode-indent-rainbow#96]
![Снимок экрана от 2020-11-16 18-12-59](https://user-images.githubusercontent.com/20415858/99256595-73708b80-2837-11eb-8771-a0e25e864967.png)

Yaml indentation are highlighted as incorrect when displaying list entries.

**Comment by oderwat** [comment]
Yes. Because it is wrong as these lines whitespace is not a multiple of you tab size. This is no linter style tool, and "wrong" does only mean you use inconsistent spacing. You should disable error mode if you don't want to see these kinds of errors.
