### ISSUE TITLE
Indent line red

### ISSUE THREAD

**Issue by ulugbekna** [oderwat/vscode-indent-rainbow#97]
Some indents are unexpectedly red, which is strange and sends incorrect signals such as "is there an error on that line?"; see image below. 

![image](https://user-images.githubusercontent.com/16353531/100084126-a673da00-2e4a-11eb-9300-d3eebfc22250.png)

**Comment by ulugbekna** [comment]
Whoops, there is a setting to disable this.

**Comment by damster101** [comment]
> Whoops, there is a setting to disable this.

Where?

**Comment by damster101** [comment]
ah
```
    "indentRainbow.ignoreErrorLanguages": [
        "*"
    ]
```
