### ISSUE TITLE
support for replacing whitespaces in the beginning of the line 

### ISSUE THREAD

**Issue by tejakunchavenkata** [oderwat/vscode-indent-rainbow#99]
whitespaces present in the beginning of the lines to be replaced with dot .

![image](https://user-images.githubusercontent.com/33462227/103389863-5d90fe80-4b37-11eb-8a03-fc26af353979.png)

`"indentRainbow.includedLanguages": [],
    "indentRainbow.ignoreLinePatterns" : [
        "/[ \t]* [*]/g", // lines begining with <whitespace><space>*
        "/[ \t]+[/]{2}/g" // lines begininning with <whitespace>//
      ],
    "indentRainbow.updateDelay": 50 ,
    "indentRainbow.colors": [
        "rgba(255,255,64,0.07)",
        "rgba(127,255,127,0.07)",
        "rgba(255,127,255,0.07)",
        "rgba(79,236,236,0.07)"
    ]
`

**Comment by oderwat** [comment]
Nothing I want to support. Just `"editor.renderWhitespace": "boundary"` or request something else from the VSCode devs.

**Comment by tejakunchavenkata** [comment]
Thanks Hans .
It worked .
